version: '3.8'

services:
  postgres:
    image: postgres:14.3 # Compare with https://devcenter.heroku.com/articles/heroku-postgresql#version-support
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample_api
    volumes:
        - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
